version: '3'

services:
  php:
    build: ./docker/php
    expose:
      - 9000
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app
    networks:
      - app_network

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:

volumes:
  database:
