#!/bin/bash

TOGGLE=$1
ON="on"
OFF="off"

if [ "$TOGGLE" = "$ON" ]
then
    [ -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini-disabled ] && mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini-disabled /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini;
    [ -f /usr/local/etc/php/conf.d/xdebug.ini-disabled ] && mv /usr/local/etc/php/conf.d/xdebug.ini-disabled /usr/local/etc/php/conf.d/xdebug.ini;
    echo "xDebug enabled";
else
    if [ "$TOGGLE" = "$OFF" ]
    then
    [ -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ] && mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini-disabled;
    [ -f /usr/local/etc/php/conf.d/xdebug.ini ] && mv /usr/local/etc/php/conf.d/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini-disabled;
    echo "xDebug disabled";
    else
       echo "Provide an on/off argument"
    fi
fi
